"""Initial migration.

Revision ID: 990ba21d8eae
Revises: f6a833feeb9f
Create Date: 2024-11-03 11:24:35.110836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '990ba21d8eae'
down_revision = 'f6a833feeb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('otp')
    op.drop_table('messages')
    op.drop_table('connected_users_of_user')
    op.drop_table('call_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connected_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('call_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ends_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['user.id'], name='call_history_connected_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='call_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='call_history_pkey')
    )
    op.create_table('connected_users_of_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connected_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connected_user_id'], ['user.id'], name='connected_users_of_user_connected_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='connected_users_of_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='connected_users_of_user_pkey')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connected_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('msg', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connected_user_id'], ['user.id'], name='messages_connected_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_table('otp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='otp_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='otp_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
